[flags]
dot_marker = false
enable_gpu_memory = true
group_processes = true
hide_avg_cpu = true
process_command = true
left_legend = false
current_usage = true
unifont_glyph = true

[colors]
table_header_color = "#7aa2f7"
all_cpu_color = "#7aa2f7"
avg_cpu_color = "#f7768e"
cpu_core_colors = ["#f7768e", "#ff9e64", "#e0af68", "#9ece6a", "#73daca", "#b4f9f8", "#2ac3de", "#7aa2f7"]
ram_color = "#9ece6a"
cache_color = "#f7768e"
swap_color = "#e0af68"
arc_color = "#73daca"
gpu_core_colors = ["#7aa2f7", "#73daca", "#b4f9f8", "#2ac3de"]
rx_color = "#9ece6a"
tx_color = "#f7768e"
border_color = "#292e42"
highlighted_border_color = "#7aa2f7"
text_color = "#c0caf5"
selected_text_color = "#15161e"
selected_bg_color = "#7aa2f7"
widget_title_color = "#c0caf5"
graph_color = "#a9b1d6"
