gui:
  theme:
    activeBorderColor:
      - "#ff9e64"
      - bold
    inactiveBorderColor:
      - "#292e42"
    searchingActiveBorderColor:
      - "#ff9e64"
      - bold
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#283457"
    cherryPickedCommitBgColor:
      - "#449dab"
    cherryPickedCommitFgColor:
      - "#3b4261"
    unstagedChangesColor:
      - red
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
